version: "3.2"
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      RABBIT_USER: guest
      RABBIT_PASS: user
      IN_FOLDER_LOCATION : ../../../infolder
      ARC_FOLDER_LOCATION : ../../../arcfolder
      RABBIT_HOST : "rabbitmq"
      RABBIT_PORT : 5672
      IN_FOLDER_UPDATE_TIME : 60000
      IN_FOLDER_MAX_UPDATE_TIME : 60000
      RABBIT_QUEUES : "AQ,ZU"
      TLAS : "z-fRqKUhqsh%&bCAc"
      DRSAP : "?2Cj%DdqeDteeVZeT?6"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
#      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmqfish